version: "3.9"
services:
  rabbit:
    image: rabbitmq:management
    hostname: rabbit
    ports:
      - 15672:15672
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://rabbit:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-file: 4
        max-size: 5m